### ISSUE TITLE
After first sign-in from mission control, no workspace is selected

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit#11] opened 2020-09-03 06:24 UTC
I clicked on Termit in the "Modely nových OFN (věda a výzkum, pracovní místa, úřední desky)" row in mission control. After sign-in to Termit, I land on a page like this:
![image](https://user-images.githubusercontent.com/718827/92078521-b5546e80-edbe-11ea-8a98-b37e42c94666.png)
When I click any of the "news items", I get:
![image](https://user-images.githubusercontent.com/718827/92111744-0a0ede00-eded-11ea-8da4-800dc445af52.png)
I want to see "pojmy", but not sure where. When I click on "Slovníky",I get "No workspace is currently selected":
![image](https://user-images.githubusercontent.com/718827/92078600-d87f1e00-edbe-11ea-934f-524be9759439.png)

🤷‍♂️

**Comment by ledsoft** [comment] 2020-09-09 06:21
Probable duplicate of https://github.com/opendata-mvcr/termit-ui/issues/5, feel free to reopen if it happens again after that one is fixed.

**Closed by ledsoft** 2020-09-09 06:21 UTC
